import { useAuthentication } from '@/queries/index';
import { Box, Button, Typography } from '@mui/material';
import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  const { user, /* logIn, logOut, */ isLoggingIn } = useAuthentication();

  return (
    <>
      <Head>
        <title>Home page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Button
          variant="contained"
          // onClick={logIn as SafeAny}
          disableFocusRipple
        >
          Login
        </Button>
        <Button variant="outlined" /* onClick={logOut as SafeAny} */>
          Logout
        </Button>
      </Box>
      <Typography variant="heading1">
        {isLoggingIn ? 'Logging in ...' : null}
      </Typography>
      <Typography variant="link">{JSON.stringify(user)}</Typography>
    </>
  );
};

export default Home;
